pipeline {
    agent any

    environment {
        APP_NAME = "SmartNest"
        IMAGE_NAME = "smartnest"
        CONTAINER_NAME = "smartnest-container"
        APP_PORT = "3000"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('smartnest') {
                    bat 'npm install'
                }
            }
        }

        stage('Test / Code Quality') {
            steps {
                dir('smartnest') {
                    bat 'npm run lint'
                }
            }
        }

        stage('Build') {
            steps {
                dir('smartnest') {
                    bat 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('smartnest') {
                    bat 'docker build -t %IMAGE_NAME% .'
                }
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker rm -f %CONTAINER_NAME% || exit 0'
                bat 'docker run -d -p %APP_PORT%:80 --name %CONTAINER_NAME% %IMAGE_NAME%'
            }
        }
    }

    post {
        success {
            echo 'SmartNest pipeline completed successfully.'
        }

        failure {
            echo 'SmartNest pipeline failed. Deployment was stopped.'
        }
    }
    
}
