pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('smartnest') {
                    bat 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('smartnest') {
                    bat 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('smartnest') {
                    bat 'docker build -t smartnest .'
                }
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker rm -f smartnest-container || exit 0'
                bat 'docker run -d -p 3000:80 --name smartnest-container smartnest'
            }
        }
    }
}